# Generated by Django 5.1.2 on 2024-10-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerequest',
            old_name='accepted',
            new_name='marked',
        ),
    ]
