# Generated by Django 5.1.2 on 2024-10-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0003_chessgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='journal_entry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='num_moves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='outcome',
            field=models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('tie', 'Tie')], default='tie', max_length=10),
        ),
    ]
